from hachoir_parser.program.elf import ElfFile
from hachoir_parser.program.exe import ExeFile
from hachoir_parser.program.python import PythonCompiledFile
from hachoir_parser.program.java import JavaCompiledClassFile
from hachoir_parser.program.prc import PRCFile
from hachoir_parser.program.nds import NdsFile
from hachoir_parser.program.snes import SNESFile
from hachoir_parser.program.nes import NESFile
from hachoir_parser.program.gameboy import GameboyFile
from hachoir_parser.program.gba import GBAFile
from hachoir_parser.program.n64 import N64File
from hachoir_parser.program.megadrive import MegaDriveFile
from hachoir_parser.program.mastersystem import MasterSystemFile
from hachoir_parser.program.pcfx import PCFXFile
from hachoir_parser.program.virtualboy import VirtualBoyFile
from hachoir_parser.program.fds import FDSFile
from hachoir_parser.program.ngp import NeoGeoPocketFile
from hachoir_parser.program.wsc import WonderSwanFile

